version: '3'

services:
  db:
    container_name: db
    image: 'mysql:5.7'
    command: --innodb-use-native-aio=0
    tty: true
    volumes:
      - ./_docker/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=delivery_api
      - MYSQL_USER=delivery
      - MYSQL_PASSWORD=delivery
    networks:
      - delivery
networks:
  delivery:
    driver: bridge
